package com.yasin.hosain.dynamicviewusingjson.utils;
public class Constants {
    public static final String JSON_KEY_TYPE = "type";
    public static final String JSON_KEY_TEXT = "text";
    public static final String JSON_KEY_TEXT_SIZE = "textSize";
    public static final String JSON_KEY_DESCRIPTION = "description";
    public static final String JSON_KEY_OPTIONS = "options";
    public static final String JSON_KEY_MODE = "mode";
    public static final String JSON_KEY_SINGLE_LINE = "singleLine";
    public static final String JSON_KEY_VIEWS = "views";
    public static final String TYPE_TEXT_VIEW = "textView";
    public static final String TYPE_EDIT_TEXT = "editText";
    public static final String TYPE_DROP_DOWN_LIST = "dropDownList";
    public static final String TYPE_CHECKBOX = "checkbox";
    public static final String TYPE_CHECKBOX_GROUP = "checkboxGroup";
    public static final String TYPE_RADIO_GROUP = "radioGroup";
    public static final String TYPE_BUTTON = "button";
    public static final String JSON_KEY_NAME = "name";
    public static final String JSON_KEY_TAG = "tag";
    public static final String JSON_IMAGE_SOURCE = "src" ;
    public static final String TYPE_IMAGE_VIEW = "imageView";
    public static final String JSON_KEY_GRAVITY = "gravity";
    public static final String JSON_KEY_HEIGHT = "height";
    public static final String JSON_KEY_WIDTH = "width";
    public static final String JSON_KEY_MARGIN = "margin";
    public static final String JSON_KEY_PADDING = "padding";
    public static final String JSON_KEY_TEXT_STYLE = "textStyle";
    public static final String JSON_KEY_HINT = "hint";
    public static final String JSON_INPUT_TYPE = "inputType";
}
